version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - npm install
      - npm run build
      - cdk synth

artifacts:
  files:
    - '**/*'
